# This one was generated by the AI itself 

import openai
import argparse
import os

# Parse command line arguments
parser = argparse.ArgumentParser(description='Interact with the latest ChatGPT engine from OpenAI')
parser.add_argument('--prompt', type=str, help='The prompt to start the conversation')
parser.add_argument('--temperature', type=float, default=0.5, help='The temperature of the generated text (default: 0.5)')
parser.add_argument('--max-tokens', type=int, default=500, help='The maximum number of tokens in the generated text (default: 50)')
parser.add_argument('--stop', type=str, default=None, help='The stopping sequence for the generated text (default: None)')
args = parser.parse_args()

# Initialize the OpenAI API client
openai.api_key = os.getenv("OPENAI_API_KEY") # Replace this with your actual API key
model_engine = "text-davinci-002" # Replace this with the model engine you want to use

# Define the function to generate text
def generate_text(prompt, temperature, max_tokens, stop):
    response = openai.Completion.create(
        engine=model_engine,
        prompt=prompt,
        temperature=temperature,
        max_tokens=max_tokens,
        stop=stop
    )
    return response.choices[0].text.strip()

# Generate text from the given prompt
if args.prompt:
    while True:
        prompt = input(args.prompt + "\n")
        if prompt == "exit":
            break
        response = generate_text(prompt, args.temperature, args.max_tokens, args.stop)
        print(response)
else:
    print("Please provide a prompt using the --prompt option.")
